server:
  port: 8443
  #ssl:
  #  key-store: classpath:keystore.jks
  #  key-store-password: password
  #  key-password: secret
spring:
  datasource:
    initialize: true
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop